name: plant_app_ui
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  date_time_format: ^2.0.1
  google_fonts: ^2.2.0
  tab_indicator_styler: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/fiddle-leaf.png
    - assets/images/Aloe-Vera.png
